# COMP9024 2019T2
# Name: Christopher Shu Chun Lam
# zID: z3460499
# Date: 29/06/2019
# Assignment 1 - Makefile

CC = gcc

all: puzzle

puzzle: puzzle.c boardADT.h boardADT.c
	CC -Wall -Werror -O3 -o puzzle puzzle.c boardADT.c